### PR TITLE
package.json: Use GitHub-style reference to wikimedia/kad

### PR DESCRIPTION
**Pull request by kostajh**
See https://gerrit.wikimedia.org/r/c/mediawiki/extensions/EventLogging/+/685098

### CODE REVIEW

**Comment by Pchelolo** [comment]
In theory, this entire thing really should be dropped from our dependencies, but there's a few blockers to that.

**Comment by kostajh** [comment]
Thanks for the merge @Pchelolo, could you please publish 0.2.2 to npmjs.com for wikimedia/service-runner/pull/237 ?

**Comment by Pchelolo** [comment]
Done!

**Comment by paladox** [comment]
This seems to force the use of ssh GitHub for installing the kad npm package. Can we revert this change?

**Pull request merged**
